baseURL                = "https://www.itix.fr/"
languageCode           = "en-us"
title                  = "Nicolas Massé"
author                 = "Nicolas Massé"
theme                  = "cocoa"
pygmentsUseClasses     = true
pygmentsCodefences     = true
enableRobotsTXT        = true

[taxonomies]
opensource             = "opensource"
topic                  = "topics"
tags                   = "tags"

[params]
include_rss            = true
latestpostscount       = 10
i18n_flags             = true
author                 = "Nicolas Massé"
description            = "Nicolas Massé's blog"
github                 = "//github.com/nmasse-itix"
px500                  = "//500px.com/nmasse"
linkedin               = "//linkedin.com/in/nicolasmasse"
#selfintro              = "TODO intro"
twitter                = "//twitter.com/nmasse_itix"
gravatar               = "006617bcd9aae1a019e1f923c8bd69e0"
#faviconfile            = "images/favicon.ico"

[menu]

[[menu.main]]
name                   = "Home"
weight                 = 10
identifier             = "home"
url                    = "/"

[[menu.main]]
name                   = "Biography"
weight                 = 20
identifier             = "biography"
url                    = "/biography/"

[[menu.main]]
name                   = "Blog"
weight                 = 30
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Open Source"
weight                 = 35
identifier             = "opensource"
url                    = "/opensource/"

[[menu.main]]
name                   = "Speaking"
weight                 = 40
identifier             = "speaking"
url                    = "/speaking/"

[[menu.main]]
name                   = "Writing"
weight                 = 50
identifier             = "writing"
url                    = "/writing/"

[[menu.main]]
name                   = "Contact"
weight                 = 60
identifier             = "contact"
url                    = "/contact/"
