[build]
publish = "public"
# Use --minify to reduce HTML file size since Google is now tracking this
# as "Core Web Vitals".
command = "./hugo --baseURL https://www.itix.fr --minify"

[build.environment] # Global
HUGO_VERSION = "0.79.1"

[context.production.environment] # Only for prod
HUGO_VERSION = "0.79.1"

[context.deploy-preview]
command = "./hugo --buildDrafts --buildFuture --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_ENABLEGITINFO = "true"

# Matrix homeserver discovery
[[headers]]
  for = "/.well-known/*"

  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
