[build]
publish = "public"
command = "hugo gen chromastyles --style=perldoc > static/css/chroma.css && hugo"

[build.environment] # Global
HUGO_VERSION = "0.42"

[context.production.environment] # Only for prod
HUGO_VERSION = "0.42"

[context.deploy-preview]
command = "hugo gen chromastyles --style=perldoc > static/css/chroma.css && hugo --buildDrafts --buildFuture --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_ENABLEGITINFO = "true"
